# Generated by Django 3.0.8 on 2020-10-21 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('New', 'New'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Open', max_length=8),
        ),
    ]
