// flow-typed signature: b83003a085ddf0ec203ab5a6e033379b
// flow-typed version: <<STUB>>/emoji-mart_v^3.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-mart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-mart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-mart/babel.config' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/anchors' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/category' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/emoji/emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/emoji/nimble-emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/not-found' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/picker/nimble-picker' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/picker/picker' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/preview' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/search' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/skins-dot' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/skins-emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/components/skins' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/polyfills/stringFromCodePoint' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/svgs' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils/data' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils/emoji-index/emoji-index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils/emoji-index/nimble-emoji-index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils/frequently' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils/shared-default-props' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils/shared-props' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-es/utils/store' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/anchors' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/category' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/emoji/emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/emoji/nimble-emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/not-found' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/picker/nimble-picker' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/picker/picker' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/preview' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/search' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/skins-dot' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/skins-emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/components/skins' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/polyfills/stringFromCodePoint' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/svgs' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils/data' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils/emoji-index/emoji-index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils/emoji-index/nimble-emoji-index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils/frequently' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils/shared-default-props' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils/shared-props' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist-modern/utils/store' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/anchors' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/category' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/emoji/emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/emoji/nimble-emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/not-found' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/picker/nimble-picker' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/picker/picker' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/preview' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/search' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/skins-dot' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/skins-emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/skins' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/polyfills/stringFromCodePoint' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/svgs' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/data' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/emoji-index/emoji-index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/emoji-index/nimble-emoji-index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/frequently' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/shared-default-props' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/shared-props' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/store' {
  declare module.exports: any;
}

declare module 'emoji-mart/prettier.config' {
  declare module.exports: any;
}

declare module 'emoji-mart/stories' {
  declare module.exports: any;
}

declare module 'emoji-mart/test/ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-mart/babel.config.js' {
  declare module.exports: $Exports<'emoji-mart/babel.config'>;
}
declare module 'emoji-mart/dist-es/components/anchors.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/anchors'>;
}
declare module 'emoji-mart/dist-es/components/category.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/category'>;
}
declare module 'emoji-mart/dist-es/components/emoji/emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/emoji/emoji'>;
}
declare module 'emoji-mart/dist-es/components/emoji/nimble-emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/emoji/nimble-emoji'>;
}
declare module 'emoji-mart/dist-es/components/not-found.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/not-found'>;
}
declare module 'emoji-mart/dist-es/components/picker/nimble-picker.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/picker/nimble-picker'>;
}
declare module 'emoji-mart/dist-es/components/picker/picker.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/picker/picker'>;
}
declare module 'emoji-mart/dist-es/components/preview.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/preview'>;
}
declare module 'emoji-mart/dist-es/components/search.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/search'>;
}
declare module 'emoji-mart/dist-es/components/skins-dot.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/skins-dot'>;
}
declare module 'emoji-mart/dist-es/components/skins-emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/skins-emoji'>;
}
declare module 'emoji-mart/dist-es/components/skins.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/components/skins'>;
}
declare module 'emoji-mart/dist-es/index' {
  declare module.exports: $Exports<'emoji-mart/dist-es'>;
}
declare module 'emoji-mart/dist-es/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es'>;
}
declare module 'emoji-mart/dist-es/polyfills/stringFromCodePoint.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/polyfills/stringFromCodePoint'>;
}
declare module 'emoji-mart/dist-es/svgs/index' {
  declare module.exports: $Exports<'emoji-mart/dist-es/svgs'>;
}
declare module 'emoji-mart/dist-es/svgs/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/svgs'>;
}
declare module 'emoji-mart/dist-es/utils/data.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils/data'>;
}
declare module 'emoji-mart/dist-es/utils/emoji-index/emoji-index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils/emoji-index/emoji-index'>;
}
declare module 'emoji-mart/dist-es/utils/emoji-index/nimble-emoji-index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils/emoji-index/nimble-emoji-index'>;
}
declare module 'emoji-mart/dist-es/utils/frequently.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils/frequently'>;
}
declare module 'emoji-mart/dist-es/utils/index' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils'>;
}
declare module 'emoji-mart/dist-es/utils/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils'>;
}
declare module 'emoji-mart/dist-es/utils/shared-default-props.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils/shared-default-props'>;
}
declare module 'emoji-mart/dist-es/utils/shared-props.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils/shared-props'>;
}
declare module 'emoji-mart/dist-es/utils/store.js' {
  declare module.exports: $Exports<'emoji-mart/dist-es/utils/store'>;
}
declare module 'emoji-mart/dist-modern/components/anchors.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/anchors'>;
}
declare module 'emoji-mart/dist-modern/components/category.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/category'>;
}
declare module 'emoji-mart/dist-modern/components/emoji/emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/emoji/emoji'>;
}
declare module 'emoji-mart/dist-modern/components/emoji/nimble-emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/emoji/nimble-emoji'>;
}
declare module 'emoji-mart/dist-modern/components/not-found.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/not-found'>;
}
declare module 'emoji-mart/dist-modern/components/picker/nimble-picker.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/picker/nimble-picker'>;
}
declare module 'emoji-mart/dist-modern/components/picker/picker.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/picker/picker'>;
}
declare module 'emoji-mart/dist-modern/components/preview.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/preview'>;
}
declare module 'emoji-mart/dist-modern/components/search.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/search'>;
}
declare module 'emoji-mart/dist-modern/components/skins-dot.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/skins-dot'>;
}
declare module 'emoji-mart/dist-modern/components/skins-emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/skins-emoji'>;
}
declare module 'emoji-mart/dist-modern/components/skins.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/components/skins'>;
}
declare module 'emoji-mart/dist-modern/index' {
  declare module.exports: $Exports<'emoji-mart/dist-modern'>;
}
declare module 'emoji-mart/dist-modern/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern'>;
}
declare module 'emoji-mart/dist-modern/polyfills/stringFromCodePoint.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/polyfills/stringFromCodePoint'>;
}
declare module 'emoji-mart/dist-modern/svgs/index' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/svgs'>;
}
declare module 'emoji-mart/dist-modern/svgs/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/svgs'>;
}
declare module 'emoji-mart/dist-modern/utils/data.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils/data'>;
}
declare module 'emoji-mart/dist-modern/utils/emoji-index/emoji-index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils/emoji-index/emoji-index'>;
}
declare module 'emoji-mart/dist-modern/utils/emoji-index/nimble-emoji-index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils/emoji-index/nimble-emoji-index'>;
}
declare module 'emoji-mart/dist-modern/utils/frequently.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils/frequently'>;
}
declare module 'emoji-mart/dist-modern/utils/index' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils'>;
}
declare module 'emoji-mart/dist-modern/utils/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils'>;
}
declare module 'emoji-mart/dist-modern/utils/shared-default-props.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils/shared-default-props'>;
}
declare module 'emoji-mart/dist-modern/utils/shared-props.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils/shared-props'>;
}
declare module 'emoji-mart/dist-modern/utils/store.js' {
  declare module.exports: $Exports<'emoji-mart/dist-modern/utils/store'>;
}
declare module 'emoji-mart/dist/components/anchors.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/anchors'>;
}
declare module 'emoji-mart/dist/components/category.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/category'>;
}
declare module 'emoji-mart/dist/components/emoji/emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/emoji/emoji'>;
}
declare module 'emoji-mart/dist/components/emoji/nimble-emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/emoji/nimble-emoji'>;
}
declare module 'emoji-mart/dist/components/not-found.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/not-found'>;
}
declare module 'emoji-mart/dist/components/picker/nimble-picker.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/picker/nimble-picker'>;
}
declare module 'emoji-mart/dist/components/picker/picker.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/picker/picker'>;
}
declare module 'emoji-mart/dist/components/preview.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/preview'>;
}
declare module 'emoji-mart/dist/components/search.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/search'>;
}
declare module 'emoji-mart/dist/components/skins-dot.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/skins-dot'>;
}
declare module 'emoji-mart/dist/components/skins-emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/skins-emoji'>;
}
declare module 'emoji-mart/dist/components/skins.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/skins'>;
}
declare module 'emoji-mart/dist/index' {
  declare module.exports: $Exports<'emoji-mart/dist'>;
}
declare module 'emoji-mart/dist/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist'>;
}
declare module 'emoji-mart/dist/polyfills/stringFromCodePoint.js' {
  declare module.exports: $Exports<'emoji-mart/dist/polyfills/stringFromCodePoint'>;
}
declare module 'emoji-mart/dist/svgs/index' {
  declare module.exports: $Exports<'emoji-mart/dist/svgs'>;
}
declare module 'emoji-mart/dist/svgs/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/svgs'>;
}
declare module 'emoji-mart/dist/utils/data.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/data'>;
}
declare module 'emoji-mart/dist/utils/emoji-index/emoji-index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/emoji-index/emoji-index'>;
}
declare module 'emoji-mart/dist/utils/emoji-index/nimble-emoji-index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/emoji-index/nimble-emoji-index'>;
}
declare module 'emoji-mart/dist/utils/frequently.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/frequently'>;
}
declare module 'emoji-mart/dist/utils/index' {
  declare module.exports: $Exports<'emoji-mart/dist/utils'>;
}
declare module 'emoji-mart/dist/utils/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils'>;
}
declare module 'emoji-mart/dist/utils/shared-default-props.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/shared-default-props'>;
}
declare module 'emoji-mart/dist/utils/shared-props.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/shared-props'>;
}
declare module 'emoji-mart/dist/utils/store.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/store'>;
}
declare module 'emoji-mart/prettier.config.js' {
  declare module.exports: $Exports<'emoji-mart/prettier.config'>;
}
declare module 'emoji-mart/stories/index' {
  declare module.exports: $Exports<'emoji-mart/stories'>;
}
declare module 'emoji-mart/stories/index.js' {
  declare module.exports: $Exports<'emoji-mart/stories'>;
}
declare module 'emoji-mart/test/ssr.js' {
  declare module.exports: $Exports<'emoji-mart/test/ssr'>;
}
