// flow-typed signature: f6ba92a97ba2e4f98ee9531e14e821bd
// flow-typed version: <<STUB>>/jquery-ui-dist_v^1.12.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-ui-dist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-ui-dist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-ui-dist/external/jquery/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui-dist/jquery-ui' {
  declare module.exports: any;
}

declare module 'jquery-ui-dist/jquery-ui.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-ui-dist/external/jquery/jquery.js' {
  declare module.exports: $Exports<'jquery-ui-dist/external/jquery/jquery'>;
}
declare module 'jquery-ui-dist/jquery-ui.js' {
  declare module.exports: $Exports<'jquery-ui-dist/jquery-ui'>;
}
declare module 'jquery-ui-dist/jquery-ui.min.js' {
  declare module.exports: $Exports<'jquery-ui-dist/jquery-ui.min'>;
}
