// flow-typed signature: 4a19528503f4c5c25972cba20fd988ea
// flow-typed version: <<STUB>>/router_v^1.3.5/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'router/lib/layer' {
  declare module.exports: any;
}

declare module 'router/lib/route' {
  declare module.exports: any;
}

// Filename aliases
declare module 'router/index' {
  declare module.exports: $Exports<'router'>;
}
declare module 'router/index.js' {
  declare module.exports: $Exports<'router'>;
}
declare module 'router/lib/layer.js' {
  declare module.exports: $Exports<'router/lib/layer'>;
}
declare module 'router/lib/route.js' {
  declare module.exports: $Exports<'router/lib/route'>;
}
