# Generated by Django 3.0.8 on 2020-08-24 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('trigger', models.CharField(choices=[('First Incoming Message', 'First Incoming Message'), ('Exact Match', 'Exact Match'), ('Contains Keyword', 'Contains Keyword'), ('Time of Incoming Message', 'Time of Incoming Message')], default='First Incoming Message', max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.Account')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.Number')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('act', models.CharField(choices=[('Send a Message', 'Send a Message'), ('Add to List', 'Add to List'), ('Remove from List', 'Remove from List'), ('Assign To', 'Assign To'), ('Close Chat', 'Close Chat')], max_length=16)),
                ('message', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automations.Automation')),
            ],
        ),
    ]
